### ISSUE TITLE
Sublassable CycloneDX::Parser::v1_5::JSON?

### ISSUE THREAD

**Issue by sjn** [Ovid/cyclonedx-parser#1]
Hei!

I just learned that CycloneDX 1.6 is out, and the work on 1.7 is going to start soon. With that in mind, and 1.6 being an incremental update to 1.5 – would it be possible to make CycloneDX::Parser::v1_5::JSON subclassable in such a way that it's possible to reuse it for the later versions of the spec? 😅

(Maybe a bit difficult to do, but I'll ask anyway. Hope that's ok.)

**Comment by Ovid** [comment]
Hi Salve.

If you like, I'd be happy to add you as a contributor, or you can take over this project. I don't have time for it right now. Have to handle client work.

It shouldn't be too hard to make it subclassable. Remove all `self->{...}` into proper accessors/mutators. I was putting this together quickly and never fixed that nit. The tests respect the objects and don't try to "reach inside", so this shouldn't break stuff (famous last words).

Best,
Ovid

**Comment by sjn** [comment]
Well sure, why not. Gotta get into it eventually anyway. 😬

**Comment by Ovid** [comment]
OK, I've sent an invite to add you as a collaborator. I'll consider this ticket closed. Thanks!
